version: '3'

services:
  db-mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=tfg
    volumes:
      - /data/mysql
  backend:
    image: backend
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db-mysql
    ports:
      - 9090:9090
    volumes:
      - /data/spring-boot-app