name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [6.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      working-directory: FrontEnd
      run: npm install
    
    - name: Download chrome
      run: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

    - name: Install chrome
      run: dpkg -i google-chrome-stable_current_amd64.deb

    - name: Build
      working-directory: FrontEnd
      run: npm run build --if-present

    - name: Testing
      working-directory: FrontEnd
      run: npm test
