name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [6.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      working-directory: FrontEnd
      run: | 
        npm install
        npm run build --if-present
        npm test
      with:
        node-version: ${{ matrix.node-version }}
      env:
        CI: true
